[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tic_tac_toe = "9kffPznNDDM4eCwLha9VacxhvoibjoPT9vHt2dH3NB9i"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "private/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

